const textoEs = {
    /* genrales */
    'general.login': 'Login',
    'general.dashboard': 'Dashboard',
    'general.aceptar': 'Aceptar',
    'general.salir': 'Salir',
    'general.archivo':'Archivo',
    'general.cancelar': 'Cancelar',
    'general.detalle':'Detalle',
    'general.sin.registros': 'Sin registros',
    'general.herramientas': 'Herramientas',
    'general.ver.detalle': 'Ver detalle',
    'drag.drop.titulo.uno':'Seleccione los archivos',
    'drag.drop.titulo.dos':'Seleccione su archivo',
    'drag.drop.titulo.tres':'Agregar elemento',
    'drag.drop.titulo.cuatro':'Ver detalle de archivos aceptados',
    'general.documentos.word':'Documentos Word',
    'general.documentos.docx':'Documentos Word (DOCX)',
    'general.documentos.doc':'Documentos Word (DOC)',
    'general.documentos.video':'Archivos de video (MP4, AVI, etc.)',
    'general.documentos.audio':'Archivos de audio (MP3, WAV, etc.)',
    'general.documentos.xlsx':'Hojas de cálculo Excel (XLSX)',
    'general.documentos.xls':'Hojas de cálculo Excel (XLS)',
    'general.documentos.pdf':'Documentos PDF',
    'general.imagenes.png':'Imágenes PNG',
    'general.imagenes.jpg':'Imágenes JPG',
    'general.imagenes.jpeg':'Imágenes JPEG', 
    /* dinamic table */
    'general.pagina': "Página",
    "general.mas": 'Más',
    "general.table.a": 'a',
    "general.table.de": 'de',
    "general.siguiente": 'Siguiente',
    "general.ultimo": "Último",
    'general.primero': 'Primero',
    'general.anterior': 'Anterior',
    'general.cargando': 'Cargando',
    'general.seleccionar.todo': 'Seleccionar todo',
    'general.buscando': 'Buscando',
    'general.en.blanco': 'En blanco',
    'genral.filtrar': 'Filtrar',
    'general.igual': 'Igual',
    'general.diferente': 'Diferente',
    'general.contiene': 'Contiene',
    'general.no.contiene': 'No contiene',
    'general.empieza.con': 'Empieza con',
    'general.termina.con': 'Termina con',
    'general.tamano.pagina': 'Tamaño de página',
    'general.aplica.filtro': 'Aplicar filtro',
    'general.restablecer.filtro': 'Restablecer filtro',
    'general.borrar.filtro': 'Borrar filtro',
    'general.sin.datos.mostrar': 'No hay datos para mostrar',
    'general.fijar.columna': 'Fijar columna',
    'general.ajustar.esta.columna': 'Ajustar esta columna',
    'genral.ajustar.todas.columnas': 'Ajustar todas las columnas',
    'general.restablecer.columnas': 'Restablecer columnas',
    'general.vacio': 'Vacío',
    'general.no.vacio': 'No vacío',
    /* inputs */
    'input.usuario': 'Usuario',
    'input.usuario.placeholder': 'Ingrese su usuario',
    'input.piso': 'Piso',
    'input.piso.placeholder': 'Seleccione las opciones deseadas',
    'input.comentarios': 'Comentarios',
    'input.comentarios.placeholder': 'Ingrese sus comentarios',
    /* input validaciones */
    'intput.validation.requerido': 'Requerido',
    'intput.validation.min.4': 'Minimo 4 caracteres',
    'intput.validation.min.20': 'Maximo 20 caracteres',
    'intput.validation.min.255': 'Maximo 255 caracteres',
};

export default textoEs;